### ISSUE TITLE
verify_id_token is now broken 

### ISSUE THREAD

**Issue by wannabeCitizen** [google/oauth2client#76]
When we try to use verify_id_token in our app, the updated version of oauth2client now tells us urllib cannot be imported.  The stacktrace looks something like this:

web_1 | from oauth2client.client import verify_id_token
web_1 | File "/usr/local/lib/python2.7/site-packages/oauth2client/client.py", line 32, in <module>
web_1 | from six.moves import urllib
web_1 | ImportError: cannot import name urllib

**Comment by skrat** [comment]
No it isn't, I'm using latest version, and still getting this error. When I import from REPL, it works, it even works when I import from REPL launched by django shell. But when I run my celery worker, this error pops up. I smell some serious hacks around Python's import machinery here.

**Comment by jek888** [comment]
Confirms the. Same problems.
Skrat, did you find solution?

**Comment by skrat** [comment]
@jek888  I had to downgrade all the way to the version that doesn't depend on `six`

**Comment by eldavido** [comment]
Confirmed that I'm also seeing this issue. I'm using Pylons on Python 2.7.8. REPL works fine like @skrat mentioned

```
(crittercism)lt-m-ramr:server dalbrecht$ python
Python 2.7.8 (default, Sep 30 2014, 16:09:59) 
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import six.moves.urllib as urllib
>>> 
```

but when I import it from within my application, I'm getting a traceback saying "ImportError: cannot import name urllib" from "from six.moves import urllib" in oauth2client.client. I'll post a fix if I find one.

**Comment by edevil** [comment]
I had this problem, but upgrading six to 1.9.0 solved it.

**Comment by dhermes** [comment]
Thanks @edevil for the confirmation! Right now [we've got][1] `six>=1.6.1`.

I'm curious about some of the other reports though.

[1]: https://github.com/google/oauth2client/blob/4fdd7f98fd56b843c7f9ad35ed5ff2f33f8454a4/setup.py#L42

**Comment by dhermes** [comment]
It seems this import should work in every version after `1.6.1` except for `1.7.1`. But `1.7.1` is broken in every way.

See below (I ran this from a virtual environment):

```bash
$ pip install six==1.4.0
$ python -c 'import six; print six.__version__; from six.moves import urllib; print urllib'
1.4.0
<module 'six.moves.urllib' (built-in)>
$ pip install six==1.4.1
$ python -c 'import six; print six.__version__; from six.moves import urllib; print urllib'
1.4.1
<module 'six.moves.urllib' (built-in)>
$ pip install six==1.5.0
$ python -c 'import six; print six.__version__; from six.moves import urllib; print urllib'
1.5.0
<module 'six.moves.urllib' (built-in)>
$ pip install six==1.5.1
$ python -c 'import six; print six.__version__; from six.moves import urllib; print urllib'
1.5.1
<module 'six.moves.urllib' (built-in)>
$ pip install six==1.5.2
$ python -c 'import six; print six.__version__; from six.moves import urllib; print urllib'
1.5.2
<module 'six.moves.urllib' (built-in)>
$ pip install six==1.6.0
$ python -c 'import six; print six.__version__; from six.moves import urllib; print urllib'
1.6.0
<module 'six.moves.urllib' (built-in)>
$ pip install six==1.6.1
$ python -c 'import six; print six.__version__; from six.moves import urllib; print urllib'
1.6.1
<module 'six.moves.urllib' (built-in)>
$ pip install six==1.7.0
$ python -c 'import six; print six.__version__; from six.moves import urllib; print urllib'
1.7.0
<module 'six.moves.urllib' (built-in)>
$ pip install six==1.7.1
$ python -c 'import six; print six.__version__; from six.moves import urllib; print urllib'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/path/to/venv/local/lib/python2.7/site-packages/six.py", line 753, in <module>
    del i, importer
NameError: name 'i' is not defined
$ pip install six==1.7.2
$ python -c 'import six; print six.__version__; from six.moves import urllib; print urllib'
1.7.2
<module 'six.moves.urllib' (built-in)>
$ pip install six==1.7.3
$ python -c 'import six; print six.__version__; from six.moves import urllib; print urllib'
1.7.3
<module 'six.moves.urllib' (built-in)>
$ pip install six==1.8.0
$ python -c 'import six; print six.__version__; from six.moves import urllib; print urllib'
1.8.0
<module 'six.moves.urllib' (built-in)>
$ pip install six==1.9.0
$ python -c 'import six; print six.__version__; from six.moves import urllib; print urllib'
1.9.0
<module 'six.moves.urllib' (built-in)>
```

**Comment by dhermes** [comment]
@edevil I'm inclined to leave this closed.

What version did you have before?

**Comment by edevil** [comment]
I had 1.1.0.

**Comment by dhermes** [comment]
Whoa. I'm curious why that wasn't caught by `six>=1.6.1`.

**Comment by edevil** [comment]
I use a requirements file with pip to install specific module versions. I had 1.1.0 for six, maybe that's why?

**Comment by dhermes** [comment]
Quite possible.

**Comment by JacobOscarson** [comment]
Anyone seen any progress on this? As far as I can see, it seems to be an old version of `six` hanging around. Referred to from other at time of writing recent places, e.g. https://github.com/mkdocs/mkdocs/issues/576, http://stackoverflow.com/questions/27656510/issues-with-six-under-django, https://groups.google.com/forum/#!topic/mkdocs/6IXq0PWVt6I

**Comment by dhermes** [comment]
@JacobOscarson If you're on a Mac it's because they ship with an old version of `six`.

Do something like

```python
>>> import six
>>> print six.__file__
/usr/local/lib/python2.7/dist-packages/six.pyc
>>> import oauth2client
>>> print oauth2client.__file__
/usr/local/lib/python2.7/dist-packages/oauth2client/__init__.pyc
```

to determine the install locations.

If `six` is not in the same `dist-packages` or `site-packages` directory as `oauth2client`, you've found your issue.

See an old [StackOverflow post][1] for some details on this, but it's likely that the old `six` version is in:

```
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
```

and that path is higher precedence on your `PYTHONPATH` than the place your `pip` installer puts packages.

You can just delete the version of `six` there and say thanks but no thanks to Apple.

[1]: http://stackoverflow.com/questions/20762667/python-doesnt-use-updated-pip-scipy-package

**Comment by jonparrott** [comment]
Alternatively, use [virtualenv](https://virtualenv.pypa.io/en/latest/) to isolate your program's dependencies from system packages.

**Comment by dhermes** [comment]
:+1: I thought of that the moment I posted my answer

**Comment by JacobOscarson** [comment]
Thanks for the suggestions! I'll have a look at them. (@jonparrot I'm already inside a virtualenv, but the virtualenv -installed `six` seems to be confused by a system package when importing sub-packages e.g. packages under `six.moves`)
