### ISSUE TITLE
Missing dependency on pyOpenSSL

### ISSUE THREAD

**Issue by 7AC** [google/oauth2client#112]
I'm running Fedora 14, i.e., python 2.7 and pyOpenSSL 0.9. According to `tox.ini` the requirement is `pyopenssl<0.14`, but the `OpenSSL.crypto.sign()` method is missing in that version (see below). What is the minimum version of pyOpenSSL required?

```
Traceback (most recent call last):
[...]
    self.service = apiclient.discovery.build( 'admin', 'v1', http=http )
  File "/usr/lib/python2.7/site-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "build/bdist.macosx-10.9-x86_64/egg/googleapiclient/discovery.py", line 198, in build
  File "/usr/lib/python2.7/site-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/oauth2client/client.py", line 530, in new_request
    self._refresh(request_orig)
  File "/usr/lib/python2.7/site-packages/oauth2client/client.py", line 744, in _refresh
    self._do_refresh_request(http_request)
  File "/usr/lib/python2.7/site-packages/oauth2client/client.py", line 768, in _do_refresh_request
    body = self._generate_refresh_request_body()
  File "/usr/lib/python2.7/site-packages/oauth2client/client.py", line 1376, in _generate_refresh_request_body
    assertion = self._generate_assertion()
  File "/usr/lib/python2.7/site-packages/oauth2client/client.py", line 1505, in _generate_assertion
    private_key, self.private_key_password), payload)
  File "/usr/lib/python2.7/site-packages/oauth2client/crypt.py", line 328, in make_signed_jwt
    signature = signer.sign(signing_input)
  File "/usr/lib/python2.7/site-packages/oauth2client/crypt.py", line 116, in sign
    return crypto.sign(self._key, message, 'sha256')
AttributeError: 'module' object has no attribute 'sign'
```

**Comment by craigcitro** [comment]
hi @7AC -- actually, i think the right requirement for pyOpenSSL should be `>=0.13`. (the `tox.ini` actually uses `0.14` for most cases, but `0.13` for a few others.)

actually, this is a little complicated, in the sense that we don't actually *require* pyOpenSSL (some parts of oauth2client work fine without it), so it's hard to specify a minimum version. (we could check at runtime, but that makes the already-messy `crypt.py` even messier.)

i'm going to leave this open, both for others who hit the same issue, and for someone else to come along and have a better idea. `;)`

**Comment by 7AC** [comment]
Thanks @craigcitro. Looks like `sign()` was introduced in 8cf4f8051e603e588554a46fa4821eead7d02075 though, which seems to be in [v0.14a1](https://github.com/pyca/pyopenssl/releases/tag/v0.14a1) so I'm not sure `0.13` will work either. The bad news for me is to get to `>=0.13` I need to upgrade to at least Fedora 18.

**Comment by dhermes** [comment]
Fedora 14 is almost 5 years old: http://en.wikipedia.org/wiki/List_of_Fedora_releases#Fedora_14

Is there a reason to stay on it?

**Comment by 7AC** [comment]
Our code base is fairly large, we have a team migrating to a more recent version but we're not quite there yet. Either way I was able to get around this by using `oauth2client.client.OAuth2WebServerFlow` and `oauth2client.file.Storage`, which seem to work fine on Fedora 14.
